### ISSUE TITLE
Cannot install npm package

### ISSUE THREAD

**Issue by robross0606** [TimMikeladze/keyv-arango#3]
Attempting to install this with `npm` results in an error:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path C:\Code\my_project\node_modules\keyv-arango\dist\cli.module.js
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Code\my_project\node_modules\keyv-arango\dist\cli.module.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I manually downloaded the tarball and it does not contain any file for `dist\cli.module.js`.  
![image](https://user-images.githubusercontent.com/2965467/232490951-e07d9345-0ae1-4d77-877b-6daf5b70bd77.png)

**Comment by TimMikeladze** [comment]
@robross0606 This issue has been fixed in https://github.com/TimMikeladze/keyv-arango/commit/492ccf36a3ab056598acd0f2973ae25c04575c0a

A new release has been published as `1.4.0`.

Thank you again for finding this bug.
